name: Update Bandwidth Data

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Update data
      env:
        API_URLS: ${{ secrets.API_URLS }}
        API_NAMES: ${{ secrets.API_NAMES }}
      run: python update_data.py
    - name: Commit and push if changed
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add bandwidth_data.json
        git commit -m "Update bandwidth data" || echo "No changes to commit"
        git push https://$PAT@github.com/${{ github.repository }}.git